#
# Build stage
#
FROM maven:3-eclipse-temurin-21-alpine as build-stage
ENV MAVEN_OPTS="-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true"
RUN mkdir -p /application-build
WORKDIR /application-build
ADD . /application-build
COPY pom.xml .
RUN --mount=type=cache,target=/root/.m2 mvn dependency:go-offline -B
COPY src src
RUN --mount=type=cache,target=/root/.m2 mvn package -Dmaven.test.skip


FROM eclipse-temurin:21
WORKDIR /app
COPY --from=build-stage /application-build/target/*.jar app.jar
EXPOSE 8083
ENTRYPOINT ["java", "-jar", "app.jar"]
